#!/bin/sh
# Render the course documents to PDF in dist/ for the submission ZIP.
#
# Documentation tooling only: it is not part of the PIM implementation, so the
# standard-library-only rule does not apply. Needs pandoc, xelatex (MacTeX),
# mermaid-cli (mmdc), and Google Chrome for mmdc (override with
# PUPPETEER_EXECUTABLE_PATH). Usage from the repository root:
#
#     sh docs/deliverables/build.sh

set -e
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
DOCS="$ROOT/docs/deliverables"
OUT="$ROOT/dist"
BUILD="$OUT/build"

for tool in pandoc xelatex mmdc; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "build: $tool not found" >&2
        exit 1
    fi
done

mkdir -p "$BUILD/diagrams"

# mmdc drives a headless browser; reuse the installed Chrome instead of a
# puppeteer download.
CHROME=${PUPPETEER_EXECUTABLE_PATH:-"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"}
printf '{"executablePath": "%s", "args": ["--no-sandbox"]}\n' "$CHROME" > "$BUILD/puppeteer.json"

for src in "$DOCS"/diagrams/*.mmd; do
    name=$(basename "$src" .mmd)
    echo "build: diagram $name"
    mmdc -q -p "$BUILD/puppeteer.json" -i "$src" -o "$BUILD/diagrams/$name.png" -s 3 -b white
done

# Wrap the plain-text coverage report so it renders as a document.
{
    echo "# Line coverage report (model/)"
    echo
    echo "Generated by \`python3 coverage_report.py\` at the source root."
    echo
    echo '```'
    cat "$ROOT/coverage.txt"
    echo '```'
} > "$BUILD/coverage.md"

render() {
    # $1 = source markdown, $2 = output name (without .pdf)
    echo "build: $2.pdf"
    pandoc "$1" \
        --from markdown \
        --pdf-engine=xelatex \
        --lua-filter="$DOCS/code-pipes.lua" \
        --resource-path="$BUILD:$DOCS:$ROOT" \
        -V geometry:margin=2cm \
        -V mainfont="Arial" \
        -V monofont="Menlo" \
        -V monofontoptions="Scale=0.85" \
        -V colorlinks=true \
        -V fontsize=10pt \
        -o "$OUT/$2.pdf"
}

render "$DOCS/SRS.md" SRS
render "$DOCS/DESIGN.md" DESIGN
render "$ROOT/DEVELOPER.md" DEVELOPER
render "$ROOT/USER.md" USER
render "$ROOT/REQUIREMENTS.md" REQUIREMENTS
render "$BUILD/coverage.md" coverage

echo "build: done; PDFs are in $OUT"
